// On-screen text per language. The TGK window itself stays in English, as the app is.
const STRINGS = {
  en: {
    open: { c: [['40', 'servers'], ['12', 'private keys'], ['3', 'places to look for a password']], note: 'root pw: Summer2024! (old?)',
      note2: 'ask ops for the VPN?', chat: 'does anyone have the staging password??', sheet: 'servers_FINAL_v7.xlsx', better: 'There is a better way.' },
    logo: { tag: 'Every server. <em>One encrypted vault.</em>', pills: ['SSH sessions', 'SFTP files', 'Credentials', 'AI agents'], os: 'Windows · Linux · macOS' },
    sessions: { kick: 'Sessions', title: 'A browser for your<br><em>infrastructure</em>',
      b: ['Browser-style tabs, drag to reorder', 'Quick connect: user@host:port', 'Search saved hosts by name or address', 'Keys, passwords, keyboard-interactive', 'Host keys verified on first connect'] },
    split: { kick: 'Split view', title: 'Every machine. <em>At a glance.</em>', lay: ['Side by side', 'Stacked', 'Grid of 4', 'Grid of 6', 'Maximized'],
      keys: ['Split right', 'Split down', 'Next pane', 'Maximize'] },
    terminal: { kick: 'Terminal', title: 'A real terminal.<br><em>Your style.</em>',
      chips: ['xterm-256color', '24-bit truecolor', 'vim · htop · tmux', 'Mouse reporting', 'Bracketed paste', 'Wide chars & emoji', 'Scrollback & selection'],
      scheme: 'Color scheme', of: 'built-in schemes' },
    files: { kick: 'Files · SFTP', title: 'Your servers’ files. <em>Right there.</em>', chips: ['Drag & drop upload', 'Built-in editor', 'Host to host'],
      drop: 'Drop to upload to /var/www/app' },
    hosts: { kick: 'Hosts & keys', title: 'Configure once.<br><em>Apply everywhere.</em>', a: 'Keys & identities', b: 'Settings inheritance', c: 'Jump hosts & tunnels',
      found: 'Found on this device', layers: ['Built-in default', 'Global', 'Group · Production', 'Host · web-01'], eff: 'Effective for web-01',
      from: ['from group Production', 'global', 'this host', 'built-in default'], hops: 'Chains of up to 4 hops', you: 'This computer' },
    agents: { kick: 'AI agents · MCP', title: 'AI on your servers. <em>On your terms.</em>',
      prompt: 'check why nginx fails on web-01',
      answer: 'nginx is back up: app.conf line 42 was missing a semicolon. Fixed, validated with nginx -t, reloaded.',
      modes: [['Off', 'Agents don’t see the host'], ['Read only', 'Reads files, read-only commands'], ['Ask', 'Every change waits for you'], ['Full', 'All but protected paths']],
      shield: 'Agents never see passwords or keys', audit: 'Every call shown live and kept in an audit log' },
    security: { kick: 'Security', title: 'Zero knowledge. <em>By design.</em>',
      cards: [['Your password', 'Never leaves this device.'], ['PBKDF2-SHA256', '600,000 iterations derive an authentication key and, via HKDF, a key-encryption key.'],
        ['Vault key', 'A random 256-bit key, wrapped by your key-encryption key.'], ['AES-256-GCM', 'Every host, group, identity and known host sealed separately, bound to its id.'],
        ['TGK server', 'Stores only opaque blobs, a verifier and hashed session tokens.']],
      iters: 'iterations', banner: 'Not even the server admin can decrypt your vault.', sub: 'A forgotten password can’t be recovered — by anyone. That’s the point.' },
    sync: { kick: 'Sync', title: 'Your server. <em>Or no server at all.</em>',
      badges: ['TOTP two-factor required', 'Per-device sessions', 'Sign out any device', 'Background sync'],
      dev: ['Windows laptop', 'Linux workstation', 'MacBook'], server: 'self-hosted', synced: 'Synced', syncing: 'Syncing…',
      local: 'This device only', localSub: 'A local SQLite vault, protected by a master password. No server at all.',
      sw: ['Upload a local vault to an account', 'Save an offline copy of an account', 'Encrypted .tgkbackup export & import', 'Keeps working offline'] },
    platforms: { kick: 'Everywhere', title: 'Windows. Linux. <em>macOS.</em>',
      notes: ['Installer for your user, no admin rights', 'AppImage: chmod +x and run', 'Apple Silicon and Intel'], upd: 'Updates itself, checksum-verified' },
    benefits: { kick: 'For teams', title: 'Built for teams that take<br><em>infrastructure seriously</em>',
      tiles: [['No SaaS lock-in', 'Self-host the sync server or run fully local. Your data stays on your infrastructure.'],
        ['No per-seat licences', 'Free and MIT-licensed. Roll it out to the whole team, contractors included.'],
        ['Open & auditable', 'Every line of code is public. Review it, fork it, build it yourself.'],
        ['End-to-end encrypted', 'Zero-knowledge vault: AES-256-GCM, PBKDF2 with 600k iterations, TOTP.'],
        ['Least-privilege automation', 'Per-host agent access: Off, Read only, Ask or Full. Secrets stay protected.'],
        ['Complete audit trail', 'Every agent call shown live, mirrored in a log tab and kept in an audit log.']] },
    community: { kick: 'Open source', title: 'Missing a feature?<br><em>Build it.</em>', l1: 'Build it yourself, send a pull request', l2: 'Or open a request — if it helps many, we build it together',
      example: 'example', votes: 'from people who need it too', steps: ['Idea', 'Issue', 'Pull request', 'main', 'Nightly', 'Release'] },
    outro: { tag: 'Every server. <em>One vault.</em>', cta: 'Download free', free: 'Free · Open source · MIT license' },
  },
  ro: {
    open: { c: [['40', 'de servere'], ['12', 'chei private'], ['3', 'locuri în care cauți o parolă']], note: 'parolă root: Vara2024! (veche?)',
      note2: 'cer VPN de la ops?', chat: 'are cineva parola de la staging??', sheet: 'servere_FINAL_v7.xlsx', better: 'Există o cale mai bună.' },
    logo: { tag: 'Toate serverele. <em>Un singur seif criptat.</em>', pills: ['Sesiuni SSH', 'Fișiere SFTP', 'Credențiale', 'Agenți AI'], os: 'Windows · Linux · macOS' },
    sessions: { kick: 'Sesiuni', title: 'Un browser pentru<br><em>infrastructura ta</em>',
      b: ['Taburi ca în browser, reordonate prin tragere', 'Conectare rapidă: user@host:port', 'Cauți serverele după nume sau adresă', 'Chei, parole, keyboard-interactive', 'Cheia serverului verificată la conectare'] },
    split: { kick: 'Ecran împărțit', title: 'Toate mașinile. <em>Dintr-o privire.</em>', lay: ['Alăturate', 'Unul sub altul', 'Grilă de 4', 'Grilă de 6', 'Maximizat'],
      keys: ['Împarte la dreapta', 'Împarte în jos', 'Panoul următor', 'Maximizează'] },
    terminal: { kick: 'Terminal', title: 'Un terminal adevărat.<br><em>Stilul tău.</em>',
      chips: ['xterm-256color', 'Truecolor pe 24 de biți', 'vim · htop · tmux', 'Suport pentru mouse', 'Bracketed paste', 'Caractere late și emoji', 'Scrollback și selecție'],
      scheme: 'Schemă de culori', of: 'scheme incluse' },
    files: { kick: 'Fișiere · SFTP', title: 'Fișierele serverelor. <em>La îndemână.</em>', chips: ['Încărcare drag & drop', 'Editor integrat', 'De la server la server'],
      drop: 'Eliberează pentru a încărca în /var/www/app' },
    hosts: { kick: 'Servere și chei', title: 'Configurezi o dată.<br><em>Se aplică peste tot.</em>', a: 'Chei și identități', b: 'Moștenirea setărilor', c: 'Jump hosts și tuneluri',
      found: 'Găsite pe acest dispozitiv', layers: ['Implicit (încorporat)', 'Global', 'Grup · Production', 'Server · web-01'], eff: 'Efectiv pentru web-01',
      from: ['din grupul Production', 'global', 'acest server', 'implicit'], hops: 'Lanțuri de până la 4 salturi', you: 'Acest calculator' },
    agents: { kick: 'Agenți AI · MCP', title: 'AI pe serverele tale. <em>După regulile tale.</em>',
      prompt: 'verifică de ce nu pornește nginx pe web-01',
      answer: 'nginx funcționează din nou: în app.conf, linia 42, lipsea un punct și virgulă. Corectat, verificat cu nginx -t, reîncărcat.',
      modes: [['Off', 'Agenții nu văd serverul'], ['Read only', 'Citește, comenzi fără efecte'], ['Ask', 'Orice modificare te așteaptă'], ['Full', 'Tot, în afară de căi protejate']],
      shield: 'Agenții nu văd niciodată parole sau chei', audit: 'Fiecare apel, afișat live și păstrat în jurnalul de audit' },
    security: { kick: 'Securitate', title: 'Zero knowledge. <em>Din proiectare.</em>',
      cards: [['Parola ta', 'Nu părăsește niciodată dispozitivul.'], ['PBKDF2-SHA256', '600.000 de iterații derivă o cheie de autentificare și, prin HKDF, o cheie de criptare a cheilor.'],
        ['Cheia seifului', 'O cheie aleatoare de 256 de biți, împachetată cu cheia ta de criptare.'], ['AES-256-GCM', 'Fiecare server, grup, identitate și known host sigilat separat, legat de id-ul lui.'],
        ['Serverul TGK', 'Stochează doar date opace, un verificator și tokenuri de sesiune hash-uite.']],
      iters: 'iterații', banner: 'Nici administratorul serverului nu îți poate decripta seiful.', sub: 'O parolă uitată nu poate fi recuperată — de nimeni. Exact asta e ideea.' },
    sync: { kick: 'Sincronizare', title: 'Serverul tău. <em>Sau deloc server.</em>',
      badges: ['Autentificare TOTP obligatorie', 'Sesiuni per dispozitiv', 'Deconectezi orice dispozitiv', 'Sincronizare în fundal'],
      dev: ['Laptop Windows', 'Stație Linux', 'MacBook'], server: 'găzduit de tine', synced: 'Sincronizat', syncing: 'Se sincronizează…',
      local: 'Doar pe acest dispozitiv', localSub: 'Un seif SQLite local, protejat de o parolă principală. Fără niciun server.',
      sw: ['Urci un seif local într-un cont', 'Salvezi o copie offline a contului', 'Export și import criptat .tgkbackup', 'Merge și offline'] },
    platforms: { kick: 'Peste tot', title: 'Windows. Linux. <em>macOS.</em>',
      notes: ['Instalare pentru utilizator, fără admin', 'AppImage: chmod +x și pornește', 'Apple Silicon și Intel'], upd: 'Se actualizează singur, cu checksum verificat' },
    benefits: { kick: 'Pentru echipe', title: 'Construit pentru echipe care iau<br><em>infrastructura în serios</em>',
      tiles: [['Fără dependență de SaaS', 'Îți găzduiești serverul de sincronizare sau lucrezi complet local. Datele rămân la tine.'],
        ['Fără licențe per utilizator', 'Gratuit, licență MIT. Îl dai întregii echipe, inclusiv colaboratorilor.'],
        ['Deschis și auditabil', 'Tot codul este public. Îl verifici, îl modifici, îl compilezi singur.'],
        ['Criptat end-to-end', 'Seif zero-knowledge: AES-256-GCM, PBKDF2 cu 600k iterații, TOTP.'],
        ['Automatizări cu acces minim', 'Acces per server pentru agenți: Off, Read only, Ask sau Full.'],
        ['Jurnal de audit complet', 'Fiecare apel al unui agent, afișat live și păstrat în jurnalul de audit.']] },
    community: { kick: 'Open source', title: 'Îți lipsește ceva?<br><em>Construiește.</em>', l1: 'O construiești singur și trimiți un pull request', l2: 'Sau deschizi o cerere — dacă ajută mulți, o facem împreună',
      example: 'exemplu', votes: 'de la cei care au nevoie de ea', steps: ['Idee', 'Cerere', 'Pull request', 'main', 'Nightly', 'Release'] },
    outro: { tag: 'Toate serverele. <em>Un singur seif.</em>', cta: 'Descarcă gratuit', free: 'Gratuit · Open source · Licență MIT' },
  },
};
